import { PRODUCT_NAME } from '../../shared/meta/meta.ts';

/** Shown for `--help` and for a bare invocation. */
export function helpText(): string {
	return [
		`${PRODUCT_NAME} — code-first deployment pipelines for Salesforce`,
		'',
		`Usage: ${PRODUCT_NAME} <command> [options]`,
		'',
		'Commands:',
		'  changes        List the metadata changes between two exact commits',
		'  plan           Build the deployment plan for a pull request',
		'  gates          Run candidate quality gates without deployment credentials',
		'  validate       Validate that plan against the configured org',
		'  deploy         Deploy a plan that has already been validated',
		'  publish-check  Publish the recorded verdict as the required GitHub check',
		'  locate-run     Print the workflow run a green check points at',
		'  locate-steps   Print workflow runs holding manual-step completions',
		'  complete-step  Record that a manual pre-deployment step was carried out',
		'  inspect-run    Verify a run bundle before reading its routing fields',
		'  rollback       Build or publish a compensating PR for a successful run',
		'  history        Build deployment history from verified run artifacts',
		'  state-audit    Show the no-database MVP runtime-state contract',
		'',
		'Options:',
		'  -h, --help            Show this help',
		'  -v, --version         Show the version',
		'      --json            Emit machine-readable output on stdout',
		'      --repo            Repository to read (default: current directory)',
		'      --base            Full SHA of the base commit',
		'      --head            Full SHA of the head commit',
		'      --repository      GitHub repository as owner/name',
		'      --pull-request    Pull request number',
		'      --environment     Environment id from docket.yml',
		'      --target-branch   Branch the pull request targets',
		'      --org-id          Skip org resolution and bind the plan to this org id',
		'      --out             Directory for run artifacts',
		'      --sf              Salesforce CLI executable (default: sf)',
		'      --wait            Minutes to wait for Salesforce (default: 33)',
		'      --validated-run   Artifacts directory of the validation to deploy',
		'      --gates-run       Artifacts directory of credential-free passing gates',
		'      --merge-commit    Commit GitHub produced by merging the pull request',
		'      --require-merged  Verify with GitHub that the pull request was merged',
		'      --workflow-run-id Workflow run the validation artifacts belong to',
		'      --workflow-run-attempt Attempt number for that workflow run',
		'      --expected-plan-identity Plan identity selected by the green check',
		"      --artifacts-expire-at ISO-8601 instant this run's artifacts expire",
		'      --details-url     Link the published check points at',
		'      --steps           Directory of manual-step completion records',
		'      --step            Name of the manual step being completed',
		'      --by              Who completed that step',
		'      --run             Recorded deployment artifacts selected for rollback',
		'      --runs            Root containing deployment run artifact directories',
		'      --create-pr       Publish the rollback as a new GitHub pull request',
		'',
	].join('\n');
}
